## gno.land
["gno.land/r/sys/params.sys"]
  token_lock.bool = true
  users_pkgpath.string = "gno.land/r/sys/users"
  validators_pkgpath.string = "gno.land/r/sys/validators"
  rewards_pkgpath.string = "gno.land/r/sys/rewards"

## gnovm
["gno.land/r/sys/params.vm"]
  namespaces.bool = true
  max_gas.int64 = 10_000_000_000
  chain_tz.string = "UTC"
  default_storage_allowance.string = "UTC"
  chain_domain.string = "gno.land"

## tm2
["gno.land/r/sys/params.tm2"]

## misc
["gno.land/r/sys/params.mix"]

## testing
# do not remove these lines. they are needed for a txtar integration test.
["gno.land/r/sys/params.test"]
  foo.string = "bar"
  foo.int64 = -1337
  foo.uint64 = 42
  foo.bool = true
  #foo.bytes = todo
